# Generated by Django 4.0.3 on 2022-03-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asterisk',
            new_name='Formulario',
        ),
    ]
